# Book settings
title: Python, Data, etc.
author: Sophie Searcy
logo: snake.png

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/artificialsoph/soph-book

launch_buttons:
  thebelab: true

execute:
  execute_notebooks: "off"

sphinx:
  extra_extensions:
    - sphinx_thebelab
  config:
    templates_path: "_templates"
